/// Deprecated: these types supported the REAPER theme API query approach,
/// which has been replaced by the INI-based theme in rack_theme.zig.
pub const ThemeColor = struct {
    description: [*:0]const u8,
    color: c_int,
};

pub const ColorTable = struct {
    activetake_tag: ThemeColor = undefined, // Active media item take bar color
    col_buttonbg: ThemeColor = undefined, // Button background
    col_cursor2: ThemeColor = undefined, // Edit cursor (alternate)
    col_cursor: ThemeColor = undefined, // Edit cursor
    guideline_color: ThemeColor = undefined, // Editing guide line color
    arrange_vgrid: ThemeColor = undefined, // Empty arrange view area vertical grid shading
    col_arrangebg: ThemeColor = undefined, // Empty arrange view area
    col_mixerbg: ThemeColor = undefined, // Empty mixer list area
    col_tracklistbg: ThemeColor = undefined, // Empty track list area
    col_envlane1_divline: ThemeColor = undefined, // Envelope lane divider line (odd tracks)
    col_envlane2_divline: ThemeColor = undefined, // Envelope lane divider line (even tracks)
    auto_item_unsel: ThemeColor = undefined, // Envelope: Unselected automation item
    col_env10: ThemeColor = undefined, // Envelope: Send pan 2
    col_env11: ThemeColor = undefined, // Envelope: Audio hardware output volume
    col_env12: ThemeColor = undefined, // Envelope: Audio hardware output pan
    col_env13: ThemeColor = undefined, // Envelope: FX parameter 1
    col_env14: ThemeColor = undefined, // Envelope: FX parameter 2
    col_env15: ThemeColor = undefined, // Envelope: FX parameter 3
    col_env16: ThemeColor = undefined, // Envelope: FX parameter 4
    col_env1: ThemeColor = undefined, // Envelope: Volume (pre-FX)
    col_env2: ThemeColor = undefined, // Envelope: Volume
    col_env3: ThemeColor = undefined, // Envelope: Pan (pre-FX)
    col_env4: ThemeColor = undefined, // Envelope: Pan
    col_env5: ThemeColor = undefined, // Envelope: Master playrate
    col_env6: ThemeColor = undefined, // Envelope: Master tempo
    col_env7: ThemeColor = undefined, // Envelope: Width / Send volume
    col_env8: ThemeColor = undefined, // Envelope: Send pan
    col_env9: ThemeColor = undefined, // Envelope: Send volume 2
    env_item_mute: ThemeColor = undefined, // Envelope: Item take mute
    env_item_pan: ThemeColor = undefined, // Envelope: Item take pan
    env_item_pitch: ThemeColor = undefined, // Envelope: Item take pitch
    env_item_vol: ThemeColor = undefined, // Envelope: Item take volume
    env_sends_mute: ThemeColor = undefined, // Envelope: Send mute
    env_track_mute: ThemeColor = undefined, // Envelope: Mute
    env_trim_vol: ThemeColor = undefined, // Envelope: Trim Volume
    mcp_fx_bypassed: ThemeColor = undefined, // FX insert text: bypassed
    mcp_fx_normal: ThemeColor = undefined, // FX insert text: normal
    mcp_fx_offlined: ThemeColor = undefined, // FX insert text: offline
    mcp_fxparm_bypassed: ThemeColor = undefined, // FX parameter text: bypassed
    mcp_fxparm_normal: ThemeColor = undefined, // FX parameter text: normal
    mcp_fxparm_offlined: ThemeColor = undefined, // FX parameter text: offline
    col_fadearm2: ThemeColor = undefined, // Fader background when automation playing
    col_fadearm3: ThemeColor = undefined, // Fader background when in inactive touch/latch
    col_fadearm: ThemeColor = undefined, // Fader background when automation recording
    col_mi_label_float: ThemeColor = undefined, // Floating media item label
    col_mi_label_float_sel: ThemeColor = undefined, // Floating media item label (selected)
    col_gridlines2: ThemeColor = undefined, // Grid lines (start of measure)
    col_gridlines3: ThemeColor = undefined, // Grid lines (start of beats)
    col_gridlines: ThemeColor = undefined, // Grid lines (in between beats)
    group_0: ThemeColor = undefined, // Group #1
    group_1: ThemeColor = undefined, // Group #2
    group_2: ThemeColor = undefined, // Group #3
    group_3: ThemeColor = undefined, // Group #4
    group_4: ThemeColor = undefined, // Group #5
    group_5: ThemeColor = undefined, // Group #6
    group_6: ThemeColor = undefined, // Group #7
    group_7: ThemeColor = undefined, // Group #8
    group_8: ThemeColor = undefined, // Group #9
    group_9: ThemeColor = undefined, // Group #10
    group_10: ThemeColor = undefined, // Group #11
    group_11: ThemeColor = undefined, // Group #12
    group_12: ThemeColor = undefined, // Group #13
    group_13: ThemeColor = undefined, // Group #14
    group_14: ThemeColor = undefined, // Group #15
    group_15: ThemeColor = undefined, // Group #16
    group_16: ThemeColor = undefined, // Group #17
    group_17: ThemeColor = undefined, // Group #18
    group_18: ThemeColor = undefined, // Group #19
    group_19: ThemeColor = undefined, // Group #20
    group_20: ThemeColor = undefined, // Group #21
    group_21: ThemeColor = undefined, // Group #22
    group_22: ThemeColor = undefined, // Group #23
    group_23: ThemeColor = undefined, // Group #24
    group_24: ThemeColor = undefined, // Group #25
    group_25: ThemeColor = undefined, // Group #26
    group_26: ThemeColor = undefined, // Group #27
    group_27: ThemeColor = undefined, // Group #28
    group_28: ThemeColor = undefined, // Group #29
    group_29: ThemeColor = undefined, // Group #30
    group_30: ThemeColor = undefined, // Group #31
    group_31: ThemeColor = undefined, // Group #32
    group_32: ThemeColor = undefined, // Group #33
    group_33: ThemeColor = undefined, // Group #34
    group_34: ThemeColor = undefined, // Group #35
    group_35: ThemeColor = undefined, // Group #36
    group_36: ThemeColor = undefined, // Group #37
    group_37: ThemeColor = undefined, // Group #38
    group_38: ThemeColor = undefined, // Group #39
    group_39: ThemeColor = undefined, // Group #40
    group_40: ThemeColor = undefined, // Group #41
    group_41: ThemeColor = undefined, // Group #42
    group_42: ThemeColor = undefined, // Group #43
    group_43: ThemeColor = undefined, // Group #44
    group_44: ThemeColor = undefined, // Group #45
    group_45: ThemeColor = undefined, // Group #46
    group_46: ThemeColor = undefined, // Group #47
    group_47: ThemeColor = undefined, // Group #48
    group_48: ThemeColor = undefined, // Group #49
    group_49: ThemeColor = undefined, // Group #50
    group_50: ThemeColor = undefined, // Group #51
    group_51: ThemeColor = undefined, // Group #52
    group_52: ThemeColor = undefined, // Group #53
    group_53: ThemeColor = undefined, // Group #54
    group_54: ThemeColor = undefined, // Group #55
    group_55: ThemeColor = undefined, // Group #56
    group_56: ThemeColor = undefined, // Group #57
    group_57: ThemeColor = undefined, // Group #58
    group_58: ThemeColor = undefined, // Group #59
    group_59: ThemeColor = undefined, // Group #60
    group_60: ThemeColor = undefined, // Group #61
    group_61: ThemeColor = undefined, // Group #62
    group_62: ThemeColor = undefined, // Group #63
    group_63: ThemeColor = undefined, // Group #64
    io_3dhl: ThemeColor = undefined, // I/O window 3D highlight
    io_3dsh: ThemeColor = undefined, // I/O window 3D shadow
    io_text: ThemeColor = undefined, // I/O window text
    inactive_take_overlay_col: ThemeColor = undefined, // Inactive take overlay color
    mcp_list_scrollbar: ThemeColor = undefined, // List scrollbar (mixer panel)
    mcp_list_scrollbar_mouseover: ThemeColor = undefined, // List scrollbar mouseover (mixer panel)
    tcp_list_scrollbar: ThemeColor = undefined, // List scrollbar (track panel)
    tcp_list_scrollbar_mouseover: ThemeColor = undefined, // List scrollbar mouseover (track panel)
    locked_overlay_col: ThemeColor = undefined, // Locked track/item overlay color
    tcplocked_color: ThemeColor = undefined, // Locked track control panel overlay color
    midi_ccbut: ThemeColor = undefined, // MIDI editor CC lane add/remove buttons
    midi_ccbut_arrow: ThemeColor = undefined, // MIDI editor CC lane button arrow
    midi_ccbut_text: ThemeColor = undefined, // MIDI editor CC lane button text
    midi_editcurs: ThemeColor = undefined, // MIDI editor cursor
    midi_endpt: ThemeColor = undefined, // MIDI editor end marker
    midi_grid1: ThemeColor = undefined, // MIDI editor grid line (between beats)
    midi_grid2: ThemeColor = undefined, // MIDI editor grid line (start of measure)
    midi_grid3: ThemeColor = undefined, // MIDI editor grid line (start of beats)
    midi_gridh: ThemeColor = undefined, // MIDI editor CC horizontal line
    midi_gridhc: ThemeColor = undefined, // MIDI editor CC horizontal center line
    midi_inline_trackbg1: ThemeColor = undefined, // MIDI inline background color (naturals)
    midi_inline_trackbg2: ThemeColor = undefined, // MIDI inline background color (sharps/flats)
    midi_itemctl: ThemeColor = undefined, // MIDI editor note controls
    midi_leftbg: ThemeColor = undefined, // MIDI piano pane background
    midi_notebg: ThemeColor = undefined, // MIDI editor note, unselected (midi_note_colormap overrides)
    midi_notefg: ThemeColor = undefined, // MIDI editor note, selected (midi_note_colormap overrides)
    midi_notemute: ThemeColor = undefined, // MIDI editor note, muted, unselected (midi_note_colormap overrides)
    midi_notemute_sel: ThemeColor = undefined, // MIDI editor note, muted, selected (midi_note_colormap overrides)
    midi_noteon_flash: ThemeColor = undefined, // MIDI piano key note-on flash
    midi_ofsn: ThemeColor = undefined, // MIDI editor note (offscreen)
    midi_ofsnsel: ThemeColor = undefined, // MIDI editor note (offscreen, selected)
    midi_pkey1: ThemeColor = undefined, // MIDI piano key color (naturals background, sharps/flats text)
    midi_pkey2: ThemeColor = undefined, // MIDI piano key color (sharps/flats background, naturals text)
    midi_pkey3: ThemeColor = undefined, // MIDI piano key color (selected)
    midi_rulerbg: ThemeColor = undefined, // MIDI editor ruler background
    midi_rulerfg: ThemeColor = undefined, // MIDI editor ruler text
    midi_selbg: ThemeColor = undefined, // MIDI editor time selection color
    midi_selpitch1: ThemeColor = undefined, // MIDI editor background color, selected pitch (naturals)
    midi_selpitch2: ThemeColor = undefined, // MIDI editor background color, selected pitch (sharps/flats)
    midi_trackbg1: ThemeColor = undefined, // MIDI editor background color (naturals)
    midi_trackbg2: ThemeColor = undefined, // MIDI editor background color (sharps/flats)
    midi_trackbg_outer1: ThemeColor = undefined, // MIDI editor background color, out of bounds (naturals)
    midi_trackbg_outer2: ThemeColor = undefined, // MIDI editor background color, out of bounds (sharps/flats)
    midieditorlist_bg2: ThemeColor = undefined, // MIDI list editor background (secondary)
    midieditorlist_bg: ThemeColor = undefined, // MIDI list editor background
    midieditorlist_fg2: ThemeColor = undefined, // MIDI list editor text (secondary)
    midieditorlist_fg: ThemeColor = undefined, // MIDI list editor text
    midieditorlist_grid: ThemeColor = undefined, // MIDI list editor grid lines
    midieditorlist_selbg2: ThemeColor = undefined, // MIDI list editor selected row (secondary)
    midieditorlist_selbg: ThemeColor = undefined, // MIDI list editor selected row
    midieditorlist_selfg2: ThemeColor = undefined, // MIDI list editor selected text (secondary)
    midieditorlist_selfg: ThemeColor = undefined, // MIDI list editor selected text
    midieditorlist_seliabg: ThemeColor = undefined, // MIDI list editor selected row (inactive)
    midieditorlist_seliafg: ThemeColor = undefined, // MIDI list editor selected text (inactive)
    midifont_col_dark: ThemeColor = undefined, // MIDI editor note text and control color (dark)
    midifont_col_dark_unsel: ThemeColor = undefined, // MIDI editor note text and control color, unselected (dark)
    midifont_col_light: ThemeColor = undefined, // MIDI editor note text and control color (light)
    midifont_col_light_unsel: ThemeColor = undefined, // MIDI editor note text and control color, unselected (light)
    midioct: ThemeColor = undefined, // MIDI editor octave line color
    midioct_inline: ThemeColor = undefined, // MIDI inline octave line color
    score_bg: ThemeColor = undefined, // MIDI notation editor background
    score_fg: ThemeColor = undefined, // MIDI notation editor staff/notation/text
    score_loop: ThemeColor = undefined, // MIDI notation editor loop points, selected pitch
    score_sel: ThemeColor = undefined, // MIDI notation editor selected staff/notation/text
    score_timesel: ThemeColor = undefined, // MIDI notation editor time selection
    col_main_3dhl: ThemeColor = undefined, // Main window 3D highlight
    col_main_3dsh: ThemeColor = undefined, // Main window 3D shadow
    col_main_bg2: ThemeColor = undefined, // Main window/transport background
    col_main_bg: ThemeColor = undefined, // Main window/transport background (v1, not sure about this)
    col_main_resize2: ThemeColor = undefined, // Main window pane resize mouseover
    col_main_text2: ThemeColor = undefined, // Main window/transport text
    col_main_textshadow: ThemeColor = undefined, // Main window text shadow (ignored if too close to text color)
    marker: ThemeColor = undefined, // Markers
    marker_lane_bg: ThemeColor = undefined, // Marker lane background
    marker_lane_text: ThemeColor = undefined, // Marker lane text
    marquee_fill: ThemeColor = undefined, // Marquee fill
    marquee_outline: ThemeColor = undefined, // Marquee outline
    marqueezoom_fill: ThemeColor = undefined, // Marquee zoom fill
    marqueezoom_outline: ThemeColor = undefined, // Marquee zoom outline
    col_explorer_sel: ThemeColor = undefined, // Media explorer selection
    col_explorer_seledge: ThemeColor = undefined, // Media explorer selection edge
    col_mi_bg2: ThemeColor = undefined, // Media item background (even tracks)
    col_mi_bg: ThemeColor = undefined, // Media item background (odd tracks)
    col_mi_fade2: ThemeColor = undefined, // Media item edges of controls
    col_mi_fades: ThemeColor = undefined, // Media item fade/volume controls
    col_mi_label: ThemeColor = undefined, // Media item label
    col_mi_label_sel: ThemeColor = undefined, // Media item label (selected)
    col_offlinetext: ThemeColor = undefined, // Media item offline text
    col_peaksedge2: ThemeColor = undefined, // Media item peaks edge highlight (even tracks)
    col_peaksedge: ThemeColor = undefined, // Media item peaks edge highlight (odd tracks)
    col_peaksedgesel2: ThemeColor = undefined, // Media item peaks edge highlight when selected (even tracks)
    col_peaksedgesel: ThemeColor = undefined, // Media item peaks edge highlight when selected (odd tracks)
    col_peaksfade2: ThemeColor = undefined, // Media item peaks when active in crossfade editor (fade-in)
    col_peaksfade: ThemeColor = undefined, // Media item peaks when active in crossfade editor (fade-out)
    col_stretchmarker: ThemeColor = undefined, // Media item stretch marker line
    col_stretchmarker_b: ThemeColor = undefined, // Media item stretch marker handle edge
    col_stretchmarker_h0: ThemeColor = undefined, // Media item stretch marker handle (1x)
    col_stretchmarker_h1: ThemeColor = undefined, // Media item stretch marker handle (>1x)
    col_stretchmarker_h2: ThemeColor = undefined, // Media item stretch marker handle (<1x)
    col_stretchmarker_text: ThemeColor = undefined, // Media item stretch marker text
    col_stretchmarker_tm: ThemeColor = undefined, // Media item transient guide handle
    col_tr1_itembgsel: ThemeColor = undefined, // Media item background selected (odd tracks)
    col_tr1_peaks: ThemeColor = undefined, // Media item peaks (odd tracks)
    col_tr1_ps2: ThemeColor = undefined, // Media item peaks when selected (odd tracks)
    col_tr2_itembgsel: ThemeColor = undefined, // Media item background selected (even tracks)
    col_tr2_peaks: ThemeColor = undefined, // Media item peaks (even tracks)
    col_tr2_ps2: ThemeColor = undefined, // Media item peaks when selected (even tracks)
    explorer_grid: ThemeColor = undefined, // Media explorer grid, markers
    explorer_pitchtext: ThemeColor = undefined, // Media explorer pitch detection text
    fadearea_color: ThemeColor = undefined, // Media item fade full area fill color
    fadezone_color: ThemeColor = undefined, // Media item fade quiet zone fill color
    item_grouphl: ThemeColor = undefined, // Media item edge when selected via grouping
    take_marker: ThemeColor = undefined, // Media item take marker
    mute_overlay_col: ThemeColor = undefined, // Muted/unsoloed track/item overlay color
    playcursor_color: ThemeColor = undefined, // Play cursor
    playrate_edited: ThemeColor = undefined, // Project play rate control when not 1.0
    areasel_fill: ThemeColor = undefined, // Razor edit area fill
    areasel_outline: ThemeColor = undefined, // Razor edit area outline
    region_lane_bg: ThemeColor = undefined, // Region lane background
    region_lane_text: ThemeColor = undefined, // Region lane text
    region: ThemeColor = undefined, // Regions
    col_routinghl1: ThemeColor = undefined, // matrix row highlight
    col_routinghl2: ThemeColor = undefined, // Routing matrix column highlight
    col_seltrack: ThemeColor = undefined, // Selected track control panel background
    selcol_tr1_bg: ThemeColor = undefined, // Selected track background (odd tracks)
    selcol_tr2_bg: ThemeColor = undefined, // Selected track background (even tracks)
    selitem_tag: ThemeColor = undefined, // Selected media item bar color
    mcp_send_midihw: ThemeColor = undefined, // Sends text: MIDI hardware
    mcp_sends_levels: ThemeColor = undefined, // Sends level
    mcp_sends_muted: ThemeColor = undefined, // Sends text: muted
    mcp_sends_normal: ThemeColor = undefined, // Sends text: normal
    docker_bg: ThemeColor = undefined, // Tab control background
    docker_selface: ThemeColor = undefined, // Tab control selected tab
    docker_shadow: ThemeColor = undefined, // Tab control shadow
    docker_text: ThemeColor = undefined, // Tab control text
    docker_text_sel: ThemeColor = undefined, // Tab control text selected tab
    docker_unselface: ThemeColor = undefined, // Tab control unselected tab
    windowtab_bg: ThemeColor = undefined, // Tab control background in windows
    col_vudoint: ThemeColor = undefined, // Theme has interlaced VU meters
    col_main_editbk: ThemeColor = undefined, // Themed window edit background
    col_main_text: ThemeColor = undefined, // Themed window text
    col_tl_bgsel: ThemeColor = undefined, // Time selection color
    col_tsigmark: ThemeColor = undefined, // Time signature change marker
    timesig_sel_bg: ThemeColor = undefined, // Time signature marker selected background
    ts_lane_bg: ThemeColor = undefined, // Time signature lane background
    ts_lane_text: ThemeColor = undefined, // Time signature lane text
    col_tl_bg: ThemeColor = undefined, // Timeline background
    col_tl_bgsel2: ThemeColor = undefined, // Timeline background (in loop points)
    col_tl_fg2: ThemeColor = undefined, // Timeline foreground (secondary markings)
    col_tl_fg: ThemeColor = undefined, // Timeline foreground
    col_toolbar_frame: ThemeColor = undefined, // Toolbar frame when floating or docked
    col_toolbar_text: ThemeColor = undefined, // Toolbar button text
    col_toolbar_text_on: ThemeColor = undefined, // Toolbar button enabled text
    toolbararmed_color: ThemeColor = undefined, // Toolbar button armed color
    col_tcp_text: ThemeColor = undefined, // Track panel text
    col_tcp_textsel: ThemeColor = undefined, // Track panel (selected) text
    col_tr1_bg: ThemeColor = undefined, // Track background (odd tracks)
    col_tr1_divline: ThemeColor = undefined, // Track divider line (odd tracks)
    col_tr2_bg: ThemeColor = undefined, // Track background (even tracks)
    col_tr2_divline: ThemeColor = undefined, // Track divider line (even tracks)
    col_trans_bg: ThemeColor = undefined, // Transport status background
    col_trans_fg: ThemeColor = undefined, // Transport status text
    col_transport_editbk: ThemeColor = undefined, // Transport edit background
    col_seltrack2: ThemeColor = undefined, // Unselected track control panel background (enabled with a checkbox above)
    col_vubot: ThemeColor = undefined, // VU meter bottom
    col_vuclip: ThemeColor = undefined, // VU meter clip indicator
    col_vuind1: ThemeColor = undefined, // VU (indicator) - no signal
    col_vuind2: ThemeColor = undefined, // VU (indicator) - low signal
    col_vuind3: ThemeColor = undefined, // VU (indicator) - med signal
    col_vuind4: ThemeColor = undefined, // VU (indicator) - hot signal
    col_vuintcol: ThemeColor = undefined, // VU meter interlace/edge color
    col_vumid: ThemeColor = undefined, // VU meter middle
    col_vumidi: ThemeColor = undefined, // VU meter midi activity
    col_vutop: ThemeColor = undefined, // VU meter top
    genlist_bg: ThemeColor = undefined, // Window list background
    genlist_fg: ThemeColor = undefined, // Window list text
    genlist_grid: ThemeColor = undefined, // Window list grid lines
    genlist_hilite: ThemeColor = undefined, // Window list highlighted text
    genlist_hilite_sel: ThemeColor = undefined, // Window list highlighted selected text
    genlist_selbg: ThemeColor = undefined, // Window list selected row
    genlist_selfg: ThemeColor = undefined, // Window list selected text
    genlist_seliabg: ThemeColor = undefined, // Window list selected row (inactive)
    genlist_seliafg: ThemeColor = undefined, // Window list selected text (inactive)
    wiring_border: ThemeColor = undefined, // Wiring: Box border
    wiring_fader: ThemeColor = undefined, // Wiring: Fader
    wiring_grid2: ThemeColor = undefined, // Wiring: Background
    wiring_grid: ThemeColor = undefined, // Wiring: Background grid lines
    wiring_horz_col: ThemeColor = undefined, // Wiring: Horizontal pin connections
    wiring_hwout: ThemeColor = undefined, // Wiring: System hardware outputs
    wiring_hwoutwire: ThemeColor = undefined, // Wiring: Hardware output wire
    wiring_media: ThemeColor = undefined, // Wiring: Media
    wiring_parent: ThemeColor = undefined, // Wiring: Master/Parent
    wiring_parentwire_border: ThemeColor = undefined, // Wiring: Master/Parent wire border
    wiring_parentwire_folder: ThemeColor = undefined, // Wiring: Master/Parent to parent folder wire
    wiring_parentwire_master: ThemeColor = undefined, // Wiring: Master/Parent to master wire
    wiring_pin_connected: ThemeColor = undefined, // Wiring: Pins connected
    wiring_pin_disconnected: ThemeColor = undefined, // Wiring: Pins disconnected
    wiring_pin_normal: ThemeColor = undefined, // Wiring: Pins normal
    wiring_recbg: ThemeColor = undefined, // Wiring: Record section background
    wiring_recinput: ThemeColor = undefined, // Wiring: System record inputs
    wiring_recinputwire: ThemeColor = undefined, // Wiring: Record input wire
    wiring_recitem: ThemeColor = undefined, // Wiring: Record section foreground
    wiring_recv: ThemeColor = undefined, // Wiring: Receives
    wiring_send: ThemeColor = undefined, // Wiring: Sends
    wiring_sendwire: ThemeColor = undefined, // Wiring: Send hanging wire
    wiring_tbg: ThemeColor = undefined, // Wiring: Box background
    wiring_ticon: ThemeColor = undefined, // Wiring: Box foreground
};

// WARNING: "dm" and "draw mode" variables are filtered out for now.
// .Adapted from XRaym's theme reader
pub const ThemeVars = struct {
    col_main_bg2: [*:0]const u8 = "Main window/transport background",
    col_main_text2: [*:0]const u8 = "Main window/transport text",
    col_main_textshadow: [*:0]const u8 = "Main window text shadow (ignored if too close to text color)",
    col_main_3dhl: [*:0]const u8 = "Main window 3D highlight",
    col_main_3dsh: [*:0]const u8 = "Main window 3D shadow",
    col_main_resize2: [*:0]const u8 = "Main window pane resize mouseover",
    col_main_text: [*:0]const u8 = "Themed window text",
    col_main_bg: [*:0]const u8 = "Themed window background",
    col_main_editbk: [*:0]const u8 = "Themed window edit background",
    // .col_nodarkmodemiscwnd: [*:0]const u8 =             "Do not use window theming on macOS dark mode" ,
    col_transport_editbk: [*:0]const u8 = "Transport edit background",
    col_toolbar_text: [*:0]const u8 = "Toolbar button text",
    col_toolbar_text_on: [*:0]const u8 = "Toolbar button enabled text",
    col_toolbar_frame: [*:0]const u8 = "Toolbar frame when floating or docked",
    toolbararmed_color: [*:0]const u8 = "Toolbar button armed color",
    // .toolbararmed_drawmode: [*:0]const u8 =             "Toolbar button armed fill mode" ,
    io_text: [*:0]const u8 = "I/O window text",
    io_3dhl: [*:0]const u8 = "I/O window 3D highlight",
    io_3dsh: [*:0]const u8 = "I/O window 3D shadow",
    genlist_bg: [*:0]const u8 = "Window list background",
    genlist_fg: [*:0]const u8 = "Window list text",
    genlist_grid: [*:0]const u8 = "Window list grid lines",
    genlist_selbg: [*:0]const u8 = "Window list selected row",
    genlist_selfg: [*:0]const u8 = "Window list selected text",
    genlist_seliabg: [*:0]const u8 = "Window list selected row (inactive)",
    genlist_seliafg: [*:0]const u8 = "Window list selected text (inactive)",
    genlist_hilite: [*:0]const u8 = "Window list highlighted text",
    genlist_hilite_sel: [*:0]const u8 = "Window list highlighted selected text",
    col_buttonbg: [*:0]const u8 = "Button background",
    col_tcp_text: [*:0]const u8 = "Track panel text",
    col_tcp_textsel: [*:0]const u8 = "Track panel (selected) text",
    col_seltrack: [*:0]const u8 = "Selected track control panel background",
    col_seltrack2: [*:0]const u8 = "Unselected track control panel background (enabled with a checkbox above)",
    tcplocked_color: [*:0]const u8 = "Locked track control panel overlay color",
    // .tcplocked_drawmode: [*:0]const u8 =                "Locked track control panel fill mode" ,
    col_tracklistbg: [*:0]const u8 = "Empty track list area",
    col_mixerbg: [*:0]const u8 = "Empty mixer list area",
    col_arrangebg: [*:0]const u8 = "Empty arrange view area",
    arrange_vgrid: [*:0]const u8 = "Empty arrange view area vertical grid shading",
    col_fadearm: [*:0]const u8 = "Fader background when automation recording",
    col_fadearm2: [*:0]const u8 = "Fader background when automation playing",
    col_fadearm3: [*:0]const u8 = "Fader background when in inactive touch/latch",
    col_tl_fg: [*:0]const u8 = "Timeline foreground",
    col_tl_fg2: [*:0]const u8 = "Timeline foreground (secondary markings)",
    col_tl_bg: [*:0]const u8 = "Timeline background",
    col_tl_bgsel: [*:0]const u8 = "Time selection color",
    // .timesel_drawmode: [*:0]const u8 =                  "Time selection fill mode" ,
    col_tl_bgsel2: [*:0]const u8 = "Timeline background (in loop points)",
    col_trans_bg: [*:0]const u8 = "Transport status background",
    col_trans_fg: [*:0]const u8 = "Transport status text",
    playrate_edited: [*:0]const u8 = "Project play rate control when not 1.0",
    col_mi_label: [*:0]const u8 = "Media item label",
    col_mi_label_sel: [*:0]const u8 = "Media item label (selected)",
    col_mi_label_float: [*:0]const u8 = "Floating media item label",
    col_mi_label_float_sel: [*:0]const u8 = "Floating media item label (selected)",
    col_mi_bg: [*:0]const u8 = "Media item background (odd tracks)",
    col_mi_bg2: [*:0]const u8 = "Media item background (even tracks)",
    col_tr1_itembgsel: [*:0]const u8 = "Media item background selected (odd tracks)",
    col_tr2_itembgsel: [*:0]const u8 = "Media item background selected (even tracks)",
    // .itembg_drawmode: [*:0]const u8 =                   "Media item background fill mode" ,
    col_tr1_peaks: [*:0]const u8 = "Media item peaks (odd tracks)",
    col_tr2_peaks: [*:0]const u8 = "Media item peaks (even tracks)",
    col_tr1_ps2: [*:0]const u8 = "Media item peaks when selected (odd tracks)",
    col_tr2_ps2: [*:0]const u8 = "Media item peaks when selected (even tracks)",
    col_peaksedge: [*:0]const u8 = "Media item peaks edge highlight (odd tracks)",
    col_peaksedge2: [*:0]const u8 = "Media item peaks edge highlight (even tracks)",
    col_peaksedgesel: [*:0]const u8 = "Media item peaks edge highlight when selected (odd tracks)",
    col_peaksedgesel2: [*:0]const u8 = "Media item peaks edge highlight when selected (even tracks)",
    // .cc_chase_drawmode: [*:0]const u8 =                 "Media item MIDI CC peaks fill mode" ,
    col_peaksfade: [*:0]const u8 = "Media item peaks when active in crossfade editor (fade-out)",
    col_peaksfade2: [*:0]const u8 = "Media item peaks when active in crossfade editor (fade-in)",
    col_mi_fades: [*:0]const u8 = "Media item fade/volume controls",
    fadezone_color: [*:0]const u8 = "Media item fade quiet zone fill color",
    // .fadezone_drawmode: [*:0]const u8 =                 "Media item fade quiet zone fill mode" ,
    fadearea_color: [*:0]const u8 = "Media item fade full area fill color",
    // .fadearea_drawmode: [*:0]const u8 =                 "Media item fade full area fill mode" ,
    col_mi_fade2: [*:0]const u8 = "Media item edges of controls",
    // .col_mi_fade2_drawmode: [*:0]const u8 =             "Media item edges of controls blend mode" ,
    item_grouphl: [*:0]const u8 = "Media item edge when selected via grouping",
    col_offlinetext: [*:0]const u8 = "Media item offline text",
    col_stretchmarker: [*:0]const u8 = "Media item stretch marker line",
    col_stretchmarker_h0: [*:0]const u8 = "Media item stretch marker handle (1x)",
    col_stretchmarker_h1: [*:0]const u8 = "Media item stretch marker handle (>1x)",
    col_stretchmarker_h2: [*:0]const u8 = "Media item stretch marker handle (<1x)",
    col_stretchmarker_b: [*:0]const u8 = "Media item stretch marker handle edge",
    // .col_stretchmarkerm: [*:0]const u8 =                "Media item stretch marker blend mode" ,
    col_stretchmarker_text: [*:0]const u8 = "Media item stretch marker text",
    col_stretchmarker_tm: [*:0]const u8 = "Media item transient guide handle",
    take_marker: [*:0]const u8 = "Media item take marker",
    selitem_tag: [*:0]const u8 = "Selected media item bar color",
    activetake_tag: [*:0]const u8 = "Active media item take bar color",
    col_tr1_bg: [*:0]const u8 = "Track background (odd tracks)",
    col_tr2_bg: [*:0]const u8 = "Track background (even tracks)",
    selcol_tr1_bg: [*:0]const u8 = "Selected track background (odd tracks)",
    selcol_tr2_bg: [*:0]const u8 = "Selected track background (even tracks)",
    col_tr1_divline: [*:0]const u8 = "Track divider line (odd tracks)",
    col_tr2_divline: [*:0]const u8 = "Track divider line (even tracks)",
    col_envlane1_divline: [*:0]const u8 = "Envelope lane divider line (odd tracks)",
    col_envlane2_divline: [*:0]const u8 = "Envelope lane divider line (even tracks)",
    mute_overlay_col: [*:0]const u8 = "Muted/unsoloed track/item overlay color",
    // .mute_overlay_mode: [*:0]const u8 =                 "Muted/unsoloed track/item overlay mode" ,
    inactive_take_overlay_col: [*:0]const u8 = "Inactive take overlay color",
    // .inactive_take_overlay_mode: [*:0]const u8 =        "Inactive take overlay mode" ,
    locked_overlay_col: [*:0]const u8 = "Locked track/item overlay color",
    // .locked_overlay_mode: [*:0]const u8 =               "Locked track/item overlay mode" ,
    marquee_fill: [*:0]const u8 = "Marquee fill",
    // .marquee_drawmode: [*:0]const u8 =                  "Marquee fill mode" ,
    marquee_outline: [*:0]const u8 = "Marquee outline",
    marqueezoom_fill: [*:0]const u8 = "Marquee zoom fill",
    // .marqueezoom_drawmode: [*:0]const u8 =              "Marquee zoom fill mode" ,
    marqueezoom_outline: [*:0]const u8 = "Marquee zoom outline",
    areasel_fill: [*:0]const u8 = "Razor edit area fill",
    // .areasel_drawmode: [*:0]const u8 =                  "Razor edit area fill mode" ,
    areasel_outline: [*:0]const u8 = "Razor edit area outline",
    // .areasel_outlinemode: [*:0]const u8 =               "Razor edit area outline mode" ,
    col_cursor: [*:0]const u8 = "Edit cursor",
    col_cursor2: [*:0]const u8 = "Edit cursor (alternate)",
    playcursor_color: [*:0]const u8 = "Play cursor",
    // .playcursor_drawmode: [*:0]const u8 =               "Play cursor fill mode" ,
    col_gridlines2: [*:0]const u8 = "Grid lines (start of measure)",
    // .col_gridlines2dm: [*:0]const u8 =                  "Grid lines (start of measure) - draw mode" ,
    col_gridlines3: [*:0]const u8 = "Grid lines (start of beats)",
    // .col_gridlines3dm: [*:0]const u8 =                  "Grid lines (start of beats) - draw mode" ,
    col_gridlines: [*:0]const u8 = "Grid lines (in between beats)",
    // .col_gridlines1dm: [*:0]const u8 =                  "Grid lines (in between beats) - draw mode" ,
    guideline_color: [*:0]const u8 = "Editing guide line color",
    // .guideline_drawmode: [*:0]const u8 =                "Editing guide fill mode" ,
    region: [*:0]const u8 = "Regions",
    region_lane_bg: [*:0]const u8 = "Region lane background",
    region_lane_text: [*:0]const u8 = "Region lane text",
    marker: [*:0]const u8 = "Markers",
    marker_lane_bg: [*:0]const u8 = "Marker lane background",
    marker_lane_text: [*:0]const u8 = "Marker lane text",
    col_tsigmark: [*:0]const u8 = "Time signature change marker",
    ts_lane_bg: [*:0]const u8 = "Time signature lane background",
    ts_lane_text: [*:0]const u8 = "Time signature lane text",
    timesig_sel_bg: [*:0]const u8 = "Time signature marker selected background",
    col_routinghl1: [*:0]const u8 = "Routing matrix row highlight",
    col_routinghl2: [*:0]const u8 = "Routing matrix column highlight",
    col_vudoint: [*:0]const u8 = "Theme has interlaced VU meters",
    col_vuclip: [*:0]const u8 = "VU meter clip indicator",
    col_vutop: [*:0]const u8 = "VU meter top",
    col_vumid: [*:0]const u8 = "VU meter middle",
    col_vubot: [*:0]const u8 = "VU meter bottom",
    col_vuintcol: [*:0]const u8 = "VU meter interlace/edge color",
    col_vumidi: [*:0]const u8 = "VU meter midi activity",
    col_vuind1: [*:0]const u8 = "VU (indicator) - no signal",
    col_vuind2: [*:0]const u8 = "VU (indicator) - low signal",
    col_vuind3: [*:0]const u8 = "VU (indicator) - med signal",
    col_vuind4: [*:0]const u8 = "VU (indicator) - hot signal",
    mcp_sends_normal: [*:0]const u8 = "Sends text: normal",
    mcp_sends_muted: [*:0]const u8 = "Sends text: muted",
    mcp_send_midihw: [*:0]const u8 = "Sends text: MIDI hardware",
    mcp_sends_levels: [*:0]const u8 = "Sends level",
    mcp_fx_normal: [*:0]const u8 = "FX insert text: normal",
    mcp_fx_bypassed: [*:0]const u8 = "FX insert text: bypassed",
    mcp_fx_offlined: [*:0]const u8 = "FX insert text: offline",
    mcp_fxparm_normal: [*:0]const u8 = "FX parameter text: normal",
    mcp_fxparm_bypassed: [*:0]const u8 = "FX parameter text: bypassed",
    mcp_fxparm_offlined: [*:0]const u8 = "FX parameter text: offline",
    tcp_list_scrollbar: [*:0]const u8 = "List scrollbar (track panel)",
    // .tcp_list_scrollbar_mode: [*:0]const u8 =           "List scrollbar (track panel) - draw mode" ,
    tcp_list_scrollbar_mouseover: [*:0]const u8 = "List scrollbar mouseover (track panel)",
    // .tcp_list_scrollbar_mouseover_mode: [*:0]const u8 = "List scrollbar mouseover (track panel) - draw mode" ,
    mcp_list_scrollbar: [*:0]const u8 = "List scrollbar (mixer panel)",
    // .mcp_list_scrollbar_mode: [*:0]const u8 =           "List scrollbar (mixer panel) - draw mode" ,
    mcp_list_scrollbar_mouseover: [*:0]const u8 = "List scrollbar mouseover (mixer panel)",
    // .mcp_list_scrollbar_mouseover_mode: [*:0]const u8 = "List scrollbar mouseover (mixer panel) - draw mode" ,
    midi_rulerbg: [*:0]const u8 = "MIDI editor ruler background",
    midi_rulerfg: [*:0]const u8 = "MIDI editor ruler text",
    midi_grid2: [*:0]const u8 = "MIDI editor grid line (start of measure)",
    // .midi_griddm2: [*:0]const u8 =                      "MIDI editor grid line (start of measure) - draw mode" ,
    midi_grid3: [*:0]const u8 = "MIDI editor grid line (start of beats)",
    // .midi_griddm3: [*:0]const u8 =                      "MIDI editor grid line (start of beats) - draw mode" ,
    midi_grid1: [*:0]const u8 = "MIDI editor grid line (between beats)",
    // .midi_griddm1: [*:0]const u8 =                      "MIDI editor grid line (between beats) - draw mode" ,
    midi_trackbg1: [*:0]const u8 = "MIDI editor background color (naturals)",
    midi_trackbg2: [*:0]const u8 = "MIDI editor background color (sharps/flats)",
    midi_trackbg_outer1: [*:0]const u8 = "MIDI editor background color, out of bounds (naturals)",
    midi_trackbg_outer2: [*:0]const u8 = "MIDI editor background color, out of bounds (sharps/flats)",
    midi_selpitch1: [*:0]const u8 = "MIDI editor background color, selected pitch (naturals)",
    midi_selpitch2: [*:0]const u8 = "MIDI editor background color, selected pitch (sharps/flats)",
    midi_selbg: [*:0]const u8 = "MIDI editor time selection color",
    // midi_selbg_drawmode: [*:0]const u8 = "MIDI editor time selection fill mode",
    midi_gridhc: [*:0]const u8 = "MIDI editor CC horizontal center line",
    // .midi_gridhcdm: [*:0]const u8 =                     "MIDI editor CC horizontal center line - draw mode" ,
    midi_gridh: [*:0]const u8 = "MIDI editor CC horizontal line",
    // .midi_gridhdm: [*:0]const u8 =                      "MIDI editor CC horizontal line - draw mode" ,
    midi_ccbut: [*:0]const u8 = "MIDI editor CC lane add/remove buttons",
    midi_ccbut_text: [*:0]const u8 = "MIDI editor CC lane button text",
    midi_ccbut_arrow: [*:0]const u8 = "MIDI editor CC lane button arrow",
    midioct: [*:0]const u8 = "MIDI editor octave line color",
    midi_inline_trackbg1: [*:0]const u8 = "MIDI inline background color (naturals)",
    midi_inline_trackbg2: [*:0]const u8 = "MIDI inline background color (sharps/flats)",
    midioct_inline: [*:0]const u8 = "MIDI inline octave line color",
    midi_endpt: [*:0]const u8 = "MIDI editor end marker",
    midi_notebg: [*:0]const u8 = "MIDI editor note, unselected (midi_note_colormap overrides)",
    midi_notefg: [*:0]const u8 = "MIDI editor note, selected (midi_note_colormap overrides)",
    midi_notemute: [*:0]const u8 = "MIDI editor note, muted, unselected (midi_note_colormap overrides)",
    midi_notemute_sel: [*:0]const u8 = "MIDI editor note, muted, selected (midi_note_colormap overrides)",
    midi_itemctl: [*:0]const u8 = "MIDI editor note controls",
    midi_ofsn: [*:0]const u8 = "MIDI editor note (offscreen)",
    midi_ofsnsel: [*:0]const u8 = "MIDI editor note (offscreen, selected)",
    midi_editcurs: [*:0]const u8 = "MIDI editor cursor",
    midi_pkey1: [*:0]const u8 = "MIDI piano key color (naturals background, sharps/flats text)",
    midi_pkey2: [*:0]const u8 = "MIDI piano key color (sharps/flats background, naturals text)",
    midi_pkey3: [*:0]const u8 = "MIDI piano key color (selected)",
    midi_noteon_flash: [*:0]const u8 = "MIDI piano key note-on flash",
    midi_leftbg: [*:0]const u8 = "MIDI piano pane background",
    midifont_col_light_unsel: [*:0]const u8 = "MIDI editor note text and control color, unselected (light)",
    midifont_col_dark_unsel: [*:0]const u8 = "MIDI editor note text and control color, unselected (dark)",
    // midifont_mode_unsel: [*:0]const u8 = "MIDI editor note text and control mode, unselected",
    midifont_col_light: [*:0]const u8 = "MIDI editor note text and control color (light)",
    midifont_col_dark: [*:0]const u8 = "MIDI editor note text and control color (dark)",
    // midifont_mode: [*:0]const u8 = "MIDI editor note text and control mode",
    score_bg: [*:0]const u8 = "MIDI notation editor background",
    score_fg: [*:0]const u8 = "MIDI notation editor staff/notation/text",
    score_sel: [*:0]const u8 = "MIDI notation editor selected staff/notation/text",
    score_timesel: [*:0]const u8 = "MIDI notation editor time selection",
    score_loop: [*:0]const u8 = "MIDI notation editor loop points, selected pitch",
    midieditorlist_bg: [*:0]const u8 = "MIDI list editor background",
    midieditorlist_fg: [*:0]const u8 = "MIDI list editor text",
    midieditorlist_grid: [*:0]const u8 = "MIDI list editor grid lines",
    midieditorlist_selbg: [*:0]const u8 = "MIDI list editor selected row",
    midieditorlist_selfg: [*:0]const u8 = "MIDI list editor selected text",
    midieditorlist_seliabg: [*:0]const u8 = "MIDI list editor selected row (inactive)",
    midieditorlist_seliafg: [*:0]const u8 = "MIDI list editor selected text (inactive)",
    midieditorlist_bg2: [*:0]const u8 = "MIDI list editor background (secondary)",
    midieditorlist_fg2: [*:0]const u8 = "MIDI list editor text (secondary)",
    midieditorlist_selbg2: [*:0]const u8 = "MIDI list editor selected row (secondary)",
    midieditorlist_selfg2: [*:0]const u8 = "MIDI list editor selected text (secondary)",
    col_explorer_sel: [*:0]const u8 = "Media explorer selection",
    // .col_explorer_seldm: [*:0]const u8 =                "Media explorer selection mode" ,
    col_explorer_seledge: [*:0]const u8 = "Media explorer selection edge",
    explorer_grid: [*:0]const u8 = "Media explorer grid, markers",
    explorer_pitchtext: [*:0]const u8 = "Media explorer pitch detection text",
    docker_shadow: [*:0]const u8 = "Tab control shadow",
    docker_selface: [*:0]const u8 = "Tab control selected tab",
    docker_unselface: [*:0]const u8 = "Tab control unselected tab",
    docker_text: [*:0]const u8 = "Tab control text",
    docker_text_sel: [*:0]const u8 = "Tab control text selected tab",
    docker_bg: [*:0]const u8 = "Tab control background",
    windowtab_bg: [*:0]const u8 = "Tab control background in windows",
    auto_item_unsel: [*:0]const u8 = "Envelope: Unselected automation item",
    col_env1: [*:0]const u8 = "Envelope: Volume (pre-FX)",
    col_env2: [*:0]const u8 = "Envelope: Volume",
    env_trim_vol: [*:0]const u8 = "Envelope: Trim Volume",
    col_env3: [*:0]const u8 = "Envelope: Pan (pre-FX)",
    col_env4: [*:0]const u8 = "Envelope: Pan",
    env_track_mute: [*:0]const u8 = "Envelope: Mute",
    col_env5: [*:0]const u8 = "Envelope: Master playrate",
    col_env6: [*:0]const u8 = "Envelope: Master tempo",
    col_env7: [*:0]const u8 = "Envelope: Width / Send volume",
    col_env8: [*:0]const u8 = "Envelope: Send pan",
    col_env9: [*:0]const u8 = "Envelope: Send volume 2",
    col_env10: [*:0]const u8 = "Envelope: Send pan 2",
    env_sends_mute: [*:0]const u8 = "Envelope: Send mute",
    col_env11: [*:0]const u8 = "Envelope: Audio hardware output volume",
    col_env12: [*:0]const u8 = "Envelope: Audio hardware output pan",
    col_env13: [*:0]const u8 = "Envelope: FX parameter 1",
    col_env14: [*:0]const u8 = "Envelope: FX parameter 2",
    col_env15: [*:0]const u8 = "Envelope: FX parameter 3",
    col_env16: [*:0]const u8 = "Envelope: FX parameter 4",
    env_item_vol: [*:0]const u8 = "Envelope: Item take volume",
    env_item_pan: [*:0]const u8 = "Envelope: Item take pan",
    env_item_mute: [*:0]const u8 = "Envelope: Item take mute",
    env_item_pitch: [*:0]const u8 = "Envelope: Item take pitch",
    wiring_grid2: [*:0]const u8 = "Wiring: Background",
    wiring_grid: [*:0]const u8 = "Wiring: Background grid lines",
    wiring_border: [*:0]const u8 = "Wiring: Box border",
    wiring_tbg: [*:0]const u8 = "Wiring: Box background",
    wiring_ticon: [*:0]const u8 = "Wiring: Box foreground",
    wiring_recbg: [*:0]const u8 = "Wiring: Record section background",
    wiring_recitem: [*:0]const u8 = "Wiring: Record section foreground",
    wiring_media: [*:0]const u8 = "Wiring: Media",
    wiring_recv: [*:0]const u8 = "Wiring: Receives",
    wiring_send: [*:0]const u8 = "Wiring: Sends",
    wiring_fader: [*:0]const u8 = "Wiring: Fader",
    wiring_parent: [*:0]const u8 = "Wiring: Master/Parent",
    wiring_parentwire_border: [*:0]const u8 = "Wiring: Master/Parent wire border",
    wiring_parentwire_master: [*:0]const u8 = "Wiring: Master/Parent to master wire",
    wiring_parentwire_folder: [*:0]const u8 = "Wiring: Master/Parent to parent folder wire",
    wiring_pin_normal: [*:0]const u8 = "Wiring: Pins normal",
    wiring_pin_connected: [*:0]const u8 = "Wiring: Pins connected",
    wiring_pin_disconnected: [*:0]const u8 = "Wiring: Pins disconnected",
    wiring_horz_col: [*:0]const u8 = "Wiring: Horizontal pin connections",
    wiring_sendwire: [*:0]const u8 = "Wiring: Send hanging wire",
    wiring_hwoutwire: [*:0]const u8 = "Wiring: Hardware output wire",
    wiring_recinputwire: [*:0]const u8 = "Wiring: Record input wire",
    wiring_hwout: [*:0]const u8 = "Wiring: System hardware outputs",
    wiring_recinput: [*:0]const u8 = "Wiring: System record inputs",
    group_0: [*:0]const u8 = "Group #1",
    group_1: [*:0]const u8 = "Group #2",
    group_2: [*:0]const u8 = "Group #3",
    group_3: [*:0]const u8 = "Group #4",
    group_4: [*:0]const u8 = "Group #5",
    group_5: [*:0]const u8 = "Group #6",
    group_6: [*:0]const u8 = "Group #7",
    group_7: [*:0]const u8 = "Group #8",
    group_8: [*:0]const u8 = "Group #9",
    group_9: [*:0]const u8 = "Group #10",
    group_10: [*:0]const u8 = "Group #11",
    group_11: [*:0]const u8 = "Group #12",
    group_12: [*:0]const u8 = "Group #13",
    group_13: [*:0]const u8 = "Group #14",
    group_14: [*:0]const u8 = "Group #15",
    group_15: [*:0]const u8 = "Group #16",
    group_16: [*:0]const u8 = "Group #17",
    group_17: [*:0]const u8 = "Group #18",
    group_18: [*:0]const u8 = "Group #19",
    group_19: [*:0]const u8 = "Group #20",
    group_20: [*:0]const u8 = "Group #21",
    group_21: [*:0]const u8 = "Group #22",
    group_22: [*:0]const u8 = "Group #23",
    group_23: [*:0]const u8 = "Group #24",
    group_24: [*:0]const u8 = "Group #25",
    group_25: [*:0]const u8 = "Group #26",
    group_26: [*:0]const u8 = "Group #27",
    group_27: [*:0]const u8 = "Group #28",
    group_28: [*:0]const u8 = "Group #29",
    group_29: [*:0]const u8 = "Group #30",
    group_30: [*:0]const u8 = "Group #31",
    group_31: [*:0]const u8 = "Group #32",
    group_32: [*:0]const u8 = "Group #33",
    group_33: [*:0]const u8 = "Group #34",
    group_34: [*:0]const u8 = "Group #35",
    group_35: [*:0]const u8 = "Group #36",
    group_36: [*:0]const u8 = "Group #37",
    group_37: [*:0]const u8 = "Group #38",
    group_38: [*:0]const u8 = "Group #39",
    group_39: [*:0]const u8 = "Group #40",
    group_40: [*:0]const u8 = "Group #41",
    group_41: [*:0]const u8 = "Group #42",
    group_42: [*:0]const u8 = "Group #43",
    group_43: [*:0]const u8 = "Group #44",
    group_44: [*:0]const u8 = "Group #45",
    group_45: [*:0]const u8 = "Group #46",
    group_46: [*:0]const u8 = "Group #47",
    group_47: [*:0]const u8 = "Group #48",
    group_48: [*:0]const u8 = "Group #49",
    group_49: [*:0]const u8 = "Group #50",
    group_50: [*:0]const u8 = "Group #51",
    group_51: [*:0]const u8 = "Group #52",
    group_52: [*:0]const u8 = "Group #53",
    group_53: [*:0]const u8 = "Group #54",
    group_54: [*:0]const u8 = "Group #55",
    group_55: [*:0]const u8 = "Group #56",
    group_56: [*:0]const u8 = "Group #57",
    group_57: [*:0]const u8 = "Group #58",
    group_58: [*:0]const u8 = "Group #59",
    group_59: [*:0]const u8 = "Group #60",
    group_60: [*:0]const u8 = "Group #61",
    group_61: [*:0]const u8 = "Group #62",
    group_62: [*:0]const u8 = "Group #63",
    group_63: [*:0]const u8 = "Group #64",
};
pub const themeVars: ThemeVars = ThemeVars{};
